version: '3.8'


services:
  chatbot2:
    container_name: chatbot2
    build:
        context: .
    environment:
        PORT: ${PORT}
        PORT_BOT: ${PORT_BOT}
        PUBLIC_PATH: ${PUBLIC_PATH}

        MONGO_URL: ${MONGO_URL}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
        MONGO_USER: ${MONGO_USER}
        MONGO_PASS: ${MONGO_PASS}

        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        MAILER_EMAIL: ${MAILER_EMAIL}
        MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
        MAILER_SERVICE: ${MAILER_SERVICE}
        PROD: ${PROD}

        ADMON_PHONE: ${ADMON_PHONE}
        ADMON_MAIL: ${ADMON_MAIL}
        JWT_SEED: ${JWT_SEED}
        WEB_SERVICE_URL: ${WEB_SERVICE_URL}
    ports:
      - 3000:3000
      - 3001:3001
  mongo-db:
      image: mongo:6.0.6
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      volumes:
        - ./mongo:/data/db
      ports:
        - 27017:27017
